<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-26T21:40:56+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'dodgeball',
    'version_installed' => '5.7.5.6',
    'locale' => 'fr_FR',
    'misc' => array(
        'access_entity_updated' => 1454966691,
        'do_page_reindex_check' => false,
    ),
    'i18n' => array(
        'choose_language_login' => null,
    ),
    'seo' => array(
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 1,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'mail' => array(
        'method' => 'smtp',
        'methods' => array(
            'smtp' => array(
                'server' => 'thebe.kreativmedia.ch',
                'username' => 'site@dodgeball.ch',
                'password' => 'afdbba1620',
                'port' => '465',
                'encryption' => 'SSL',
            ),
        ),
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
);
